spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vet
    username: daniel
    password: Kirita21&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

